// Test data for all states
export const TEST_STATE_DATA = {
  Alabama: { party: "red", value: 0.7 },
  Alaska: { party: "red", value: 0.6 },
  Arizona: { party: "blue", value: 0.1 },
  Arkansas: { party: "red", value: 0.8 },
  California: { party: "blue", value: 0.9 },
  Colorado: { party: "blue", value: 0.6 },
  Connecticut: { party: "blue", value: 0.8 },
  Delaware: { party: "blue", value: 0.7 },
  Florida: { party: "red", value: 0.1 },
  Georgia: { party: "blue", value: 0.1 },
  Hawaii: { party: "blue", value: 0.9 },
  Idaho: { party: "red", value: 0.8 },
  Illinois: { party: "blue", value: 0.7 },
  Indiana: { party: "red", value: 0.6 },
  Iowa: { party: "red", value: 0.5 },
  Kansas: { party: "red", value: 0.7 },
  Kentucky: { party: "red", value: 0.7 },
  Louisiana: { party: "red", value: 0.7 },
  Maine: { party: "blue", value: 0.6 },
  Maryland: { party: "blue", value: 0.8 },
  Massachusetts: { party: "blue", value: 0.9 },
  Michigan: { party: "blue", value: 0.1 },
  Minnesota: { party: "blue", value: 0.6 },
  Mississippi: { party: "red", value: 0.7 },
  Missouri: { party: "red", value: 0.6 },
  Montana: { party: "red", value: 0.6 },
  Nebraska: { party: "red", value: 0.7 },
  Nevada: { party: "blue", value: 0.1 },
  "New Hampshire": { party: "blue", value: 0.1 },
  "New Jersey": { party: "blue", value: 0.7 },
  "New Mexico": { party: "blue", value: 0.6 },
  "New York": { party: "blue", value: 0.8 },
  "North Carolina": { party: "red", value: 0.1 },
  "North Dakota": { party: "red", value: 0.7 },
  Ohio: { party: "red", value: 0.1 },
  Oklahoma: { party: "red", value: 0.8 },
  Oregon: { party: "blue", value: 0.7 },
  Pennsylvania: { party: "blue", value: 0.1 },
  "Rhode Island": { party: "blue", value: 0.8 },
  "South Carolina": { party: "red", value: 0.6 },
  "South Dakota": { party: "red", value: 0.7 },
  Tennessee: { party: "red", value: 0.7 },
  Texas: { party: "red", value: 0.9 },
  Utah: { party: "red", value: 0.8 },
  Vermont: { party: "blue", value: 0.8 },
  Virginia: { party: "blue", value: 0.1 },
  Washington: { party: "blue", value: 0.7 },
  "West Virginia": { party: "red", value: 0.8 },
  Wisconsin: { party: "blue", value: 0.1 },
  Wyoming: { party: "red", value: 0.8 },
} as const;
